import type { RoomType } from "../lighting/room";

export const HOUSE_ROOMS: RoomType[] = [
  {
    id: "A",
    floor: 2,
    label: "living",
    name: "Living Room",
    emoji: "🛋️",
    on: false,
    color: "#FF3EB5",
  },
  {
    id: "B",
    floor: 2,
    label: "pieza1",
    name: "Pieza 1",
    emoji: "🛏️",
    on: false,
    color: "#FF6B9D",
  },
  {
    id: "A",
    floor: 1,
    label: "cocina",
    name: "Cocina",
    emoji: "🍳",
    on: false,
    color: "#8B35FF",
  },
  {
    id: "B",
    floor: 1,
    label: "pieza2",
    name: "Pieza 2",
    emoji: "🛏️",
    on: false,
    color: "#FFB800",
  },
  {
    id: "A",
    floor: 0,
    label: "oficina",
    name: "Oficina",
    emoji: "🏢",
    on: false,
    color: "#00DCFF",
  },
  {
    id: "B",
    floor: 0,
    label: "pieza 3",
    name: "Pieza 3",
    emoji: "🛏️",
    on: false,
    color: "#EF5778",
  },
  // {
  //   id: "B",
  //   floor: 3,
  //   label: "terraza",
  //   name: "Terraza",
  //   emoji: "✨",
  //   on: false,
  //   color: "#8B35FF",
  // },
];
